name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: Delete Preview Worker
    runs-on: ubuntu-latest

    steps:
      - name: Delete Preview Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PRODUCTION_API_TOKEN }}
          accountId: 2f84630cfef8a6b13712d41a0e8d9afc
          command: delete --name crate-app-pr-${{ github.event.pull_request.number }} --force

